bases:
  - ../../base/db
  - ../../base/app

resources:
  - pv.yml
  - pvc.yml
images:
  - name: inventory-image
    newName: mifedirko/inventory-system
    newTag: 0.0.1

configMapGenerator:
  - name: app-configmap
    literals:
      - SPRING_PROFILES_ACTIVE=local