apiVersion: v1
kind: Service
metadata:
  name: inventory-backend-service
  labels:
    app: inventory
spec:
  # expose service outside cluster
  type: NodePort
  ports:
    - name: app-port
      port: 80
      targetPort: application
      protocol: TCP
  selector:
    tier: app